id: PB9296EBB
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA1KG513
  instance_id: http://purl.bdrc.io/resource/IE1KG513
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - ཨ་ཆུང་གནམ་རྫོང་གི་ལོ་རྒྱུས།
  alt_title:
    zh-latn-pinyin-x-ndia:
    - zang chuan fo jiao hou huang sheng di a qiong nan zong si jian shi
    en-x-mixed:
    - Phyi dar bstan paʼi gnas mchog Mdo-smad A-chuṅ-gnam-rdzoṅ gi lo rgyus bden gtam
      lha yi rol mo źes bya ba bźugs so /Śes-rab-rgya-mtshos brtsams.
  author: http://purl.bdrc.io/resource/P1KG517
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  volumes:
    cdfe0c1a90374d3c8477f9559b0c25dd:
      title: པོད ༡་ཨ་ཆུང་གནམ་རྫོང་གི་ལོ་རྒྱུས
      volume_number: 1
      base_file: UT1KG513_I1KG524_0000.txt
      reference: http://purl.bdrc.io/resource/VLB624F10A52C92424
      image_group: I1KG524
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/MW1KG513
  - http://purl.bdrc.io/resource/W1KG513
  ocr_software: Namsel
created_at: '2021-12-22T10:47:34.674953'
last_modified_at: '2021-12-22T10:47:34.674959'
statistics:
  total_words: 29328
  total_non_words: 3282
quality:
  non_words_ratio: 0.11
